import { Flex, Text } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <Flex height="100vh" width="100%" backgroundColor="gray.800" justifyContent="center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex height="100%" width="50%" justifyContent="space-evenly" alignItems="center">
        <a href="/page1">
          <Flex width="200px" height="200px" backgroundColor="gray.500" alignItems="center" justifyContent="center">
            <Text>Page 1</Text>
          </Flex>
        </a>

        <a href="/page2">
          <Flex width="200px" height="200px" backgroundColor="gray.500" alignItems="center" justifyContent="center">
            <Text>Page 2</Text>
          </Flex>
        </a>
      </Flex>
    </Flex>
  );
}
